- .gitignore
- .travis.yml
- Dockerfile
- autoconfigure-storage/pom.xml
- docker-entrypoint.bash
- server/pom.xml
- storage/pom.xml
- translation/pom.xml
* Add `.gitignore` file to make sure unintended files are not added.
* Add `.travis.yaml` to do automated CI builds.
* Add `Dockerfile` to create docker image (very useful when deploying to kuberentes)
> Add build support files

- collector/src/main/resources/stackdriver-zipkin-server-shared.yml
- collector/src/main/resources/stackdriver-zipkin-server.yml
@adriancole @kevinmdavis 
Fix for this change https://github.com/GoogleCloudPlatform/stackdriver-zipkin/commit/7beea93c6e7f53ae7ea2387a4241a566b2cf5bb7
> Fixed yaml configs

- README.md
- samples/kube-manifest.sample.yaml
> Update container path to use standard Google Container Registry bucket

- README.md
> Add Maven central badge

- pom.xml
- storage/pom.xml
- translation/pom.xml
- translation/src/main/java/com/google/cloud/trace/zipkin/translation/SpanTranslator.java
- translation/src/test/java/com/google/cloud/trace/zipkin/translation/LabelExtractorTest.java
Force GRPC upgrade to pickup https://github.com/netty/netty/commit/94d7557dead5e7780769d44bbb4aa7530149ca34 that supposedly fixes memory leak.
> Force GRPC/Netty upgrade 

- pom.xml
All dependencies still seems to be in tact:
```
denyska$ ls -ltr  /Users/denyska/Projects/stackdriver-adapter-unzipped/BOOT-INF/lib/
-rw-r--r--  1 denyska  eng    33031 Dec  8  2012 jsr305-3.0.0.jar
-rw-r--r--  1 denyska  eng    63777 Apr 10  2013 validation-api-1.1.0.Final.jar
-rw-r--r--  1 denyska  eng    95806 Apr 25  2013 javax.servlet-api-3.1.0.jar
-rw-r--r--  1 denyska  eng    26366 Apr 26  2013 javax.annotation-api-1.2.jar
-rw-r--r--  1 denyska  eng    36611 May 10  2013 javax.websocket-api-1.0.jar
-rw-r--r--  1 denyska  eng    53217 Mar 23  2014 asm-5.0.1.jar
-rw-r--r--  1 denyska  eng    41718 Mar 23  2014 asm-commons-5.0.1.jar
-rw-r--r--  1 denyska  eng    29038 Mar 23  2014 asm-tree-5.0.1.jar
-rw-r--r--  1 denyska  eng   271400 Jul 21  2014 google-http-client-1.19.0.jar …
```
> Upgrade zipkin and grpc-consumer

- translation/src/main/java/com/google/cloud/trace/zipkin/translation/LabelExtractor.java
- translation/src/test/java/com/google/cloud/trace/zipkin/translation/LabelExtractorTest.java
This PR adds two new labels to all server spans: 
`zipkin.io/endpoint.ipv4` 
`zipkin.io/endpoint.ipv6 `
> Extract Zipkin endpoints

- autoconfigure-storage/src/main/java/com/google/cloud/trace/zipkin/autoconfigure/ZipkinStackdriverStorageAutoConfiguration.java
- collector/src/main/java/com/google/cloud/trace/zipkin/EnableStackdriverCollector.java
- collector/src/main/java/com/google/cloud/trace/zipkin/StackdriverZipkinCollector.java
- collector/src/test/java/com/google/cloud/trace/zipkin/StackdriverMockServer.java
- collector/src/test/java/com/google/cloud/trace/zipkin/ZipkinCollectorIntegrationTest.java
- pom.xml
- storage/src/main/java/com/google/cloud/trace/zipkin/StackdriverSpanConsumer.java
- storage/src/main/java/com/google/cloud/trace/zipkin/StackdriverStorageComponent.java
- storage/src/test/java/com/google/cloud/trace/zipkin/StackdriverStorageComponentTest.java
- translation/pom.xml
- translation/src/main/java/com/google/cloud/trace/zipkin/translation/LabelExtractor.java
- translation/src/main/java/com/google/cloud/trace/zipkin/translation/SpanTranslator.java
- translation/src/main/java/com/google/cloud/trace/zipkin/translation/TraceTranslator.java
- translation/src/test/java/com/google/cloud/trace/zipkin/translation/LabelExtractorTest.java
- translation/src/test/java/com/google/cloud/trace/zipkin/translation/SpanTranslatorTest.java
- translation/src/test/java/com/google/cloud/trace/zipkin/translation/TraceTranslatorTest.java
Apologies for the formatting changes - I was finding style inconsistencies and having trouble writing the code without a consistent style definition, so I put everything through google-java-format which I believe is the standard for GoogleCloudPlatform projects. If it's too much trouble to include reformatting here, I can try creating a PR with just the logic changes, but it'll be quite some IDE fighting...
> Migrate business logic to use native zipkin2 API.

- autoconfigure/storage-stackdriver/pom.xml
Changing the build layout as per the Zipkin-Layout-Factory
> Layout changes for the collector and storage using zipkin layout factory

- translation-stackdriver/src/main/java/zipkin2/translation/stackdriver/LabelExtractor.java
- translation-stackdriver/src/test/java/zipkin2/translation/stackdriver/LabelExtractorTest.java
- translation-stackdriver/src/test/java/zipkin2/translation/stackdriver/SpanTranslatorTest.java
By popular demand...
Fixes #92
> Removes zipkin.io label prefix

- sender-stackdriver/src/main/java/zipkin2/reporter/stackdriver/internal/AwaitableUnaryClientCallListener.java
- sender-stackdriver/src/test/java/zipkin2/reporter/stackdriver/internal/UnaryClientCallTest.java
> Limit trace send waiting to 5 seconds

- pom.xml
> Enable existing JUnit 4 tests and run integration tests on verify

- .dockerignore
- docker/Dockerfile
- docker/README.md
Like https://github.com/openzipkin/zipkin-aws/pull/143 but for GCP
> Add Dockerfile to build master.

- README.md
I was vacillating between adding to README and creating/linking to a new page.
Fixes #133.
> Add basic troubleshooting steps

- sender-stackdriver/src/test/java/zipkin2/reporter/stackdriver/ITStackdriverSender.java
- translation-stackdriver/src/main/java/zipkin2/translation/stackdriver/SpanTranslator.java
- translation-stackdriver/src/test/java/zipkin2/translation/stackdriver/SpanTranslatorTest.java
> Set Stackdriver Span displayName to unknown if Zipkin Span name is empty

- .mvn/wrapper/maven-wrapper.properties
- autoconfigure/storage-stackdriver/pom.xml
- autoconfigure/storage-stackdriver/src/test/java/zipkin2/storage/stackdriver/ITZipkinStackdriverStorage.java
- pom.xml
- sender-stackdriver/src/test/java/zipkin2/reporter/stackdriver/ITStackdriverSender.java
I raised another issue about the dependency sprawl of oauth
> Updates to latest versions of things, notable Zipkin 2.17

- docker/Dockerfile.release
- docker/hooks/build
Mostly same as https://github.com/openzipkin/zipkin/pull/2846
> Add release Dockerfile for zipkin-gcp

- sender-stackdriver/src/test/java/zipkin2/reporter/stackdriver/ITStackdriverSender.java
intellij noticed there was an ignored comparison
> Really assert in sender test

- benchmarks/pom.xml
- docker/Dockerfile.release
- docker/README.md
- docker/hooks/build
- module/storage-stackdriver/src/test/java/zipkin2/storage/stackdriver/ZipkinStackdriverStorageIntegrationTest.java
- pom.xml
- sender-stackdriver/pom.xml
- storage-stackdriver/src/test/java/zipkin2/storage/stackdriver/StackdriverSpanConsumerTest.java
verified through the test docker image
> updates to latest

- .travis.yml
- RELEASE.md
- benchmarks/pom.xml
- pom.xml
- travis/publish.sh
See https://github.com/openzipkin/zipkin/pull/3286
> Switches dockerhub auth to token and skips deploying benchmarks

- .github/workflows/docker-tests.yml
- .github/workflows/docker/docker-compose.test.yml
> Fixed GitHub Actions verification script

- docker/Dockerfile
- pom.xml
Needed this audit find fixed in my cluster so you get to enjoy as well 😄
> chore: Update Zipkin to fix CVE-2022-37434

- .github/workflows/create_release.yml
> ci: fixes comment on why JDK 17

- docker/Dockerfile
- pom.xml
This is in preparation of doing a release to get the fix out for https://github.com/openzipkin/zipkin-gcp/issues/224
> Bumps dependencies
