openzipkin/zipkin-gcp

translation/src/main/java/com/google/cloud/trace/zipkin/translation/TraceTranslator.java, translation/src/test/java/com/google/cloud/trace/zipkin/translation/TraceTranslatorTest.java
Change ID translation so that when translating from 64-bits to 128-bits, all 128 bits in the output may be used. This helps when the Stackdriver API returns traces sorted by ascending Trace IDs. A project with Stackdriver and Zipkin traces would likely return only Zipkin traces whereas we'd prefer that it return a random mix of both.
=> Change Zipkin to Stackdriver ID translation to use entire 128-bit range.

autoconfigure-storage/pom.xml, collector/pom.xml, pom.xml, storage/pom.xml, translation/pom.xml, translation/src/main/java/com/google/cloud/trace/zipkin/translation/TraceTranslator.java, translation/src/test/java/com/google/cloud/trace/zipkin/translation/TraceTranslatorTest.java
This changes to the latest version of Zipkin and adjusts the code to use
128-bit trace ids as defined by Zipkin. This fills high bits with zero
when the trace doesn't have high bits set. This would occur when 64-bit
trace IDs are in use.
=> Updates to latest zipkin and switches to 128-bit trace IDs

collector/pom.xml
Service can either started as executable `./collector/target/collector-0.1.1-SNAPSHOT.jar`, either can be installed as init.d service (that is what I plan to do) 
> denyska$ ./collector/target/collector-0.1.1-SNAPSHOT.jar 
> 
>   .   ____          _            __ _ _
>  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
> ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
>  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
>   '  |____| .__|_| |_|_| |_\__, | / / / /
>  =========|_|==============|___/=/_/_/_/
>  :: Spring Boot ::        (v1.4.1.RELEASE)
> 
> 2016-12-20 10:12:40.582  INFO 91472 --- [           main] c.g.c.t.z.StackdriverZipkinCollector     : Starting StackdriverZipkinCollector on denyska
=> Create executable JAR instead: it can be used as init.d service

README.md
Made README.md more explicit: it was bit unclear how to run adapter within docker w/o credentials.
=> Added env variables to Docker runner

autoconfigure-storage/pom.xml, autoconfigure-storage/src/main/java/com/google/cloud/trace/zipkin/autoconfigure/ZipkinStackdriverStorageAutoConfiguration.java, autoconfigure-storage/src/main/java/com/google/cloud/trace/zipkin/autoconfigure/ZipkinStackdriverStorageProperties.java, pom.xml, storage/pom.xml, storage/src/test/java/com/google/cloud/trace/zipkin/StackdriverStorageComponentTest.java, translation/pom.xml
Before the change com.google.cloud.trace.zipkin.StackdriverStorageComponent was essentially single-threaded as ThreadPoolTaskExecutor it was using was configured with default values: corePoolSize = 1, maxPoolSize = Integer.MAX_VALUE, queueCapacity = Integer.MAX_VALUE 
From JAVA doc of java.util.concurrent.ThreadPoolExecutor
>  * When a new task is submitted in method {@link #execute(Runnable)},
>  * and fewer than corePoolSize threads are running, a new thread is
>  * created to handle the request, even if other worker threads are
>  * idle.  If there are more than corePoolSize but less than
>  * maximumPoolSize threads running, a new thread will be created only
>  * if the queue is full. 
That means unless queue reaches Integer.MAX_VALUE  no new threads would be allocated.
=> Made executor service configurable

autoconfigure-storage/src/main/java/com/google/cloud/trace/zipkin/autoconfigure/ZipkinStackdriverStorageAutoConfiguration.java, collector/src/test/java/com/google/cloud/trace/zipkin/ZipkinCollectorIntegrationTest.java, pom.xml, storage/pom.xml, storage/src/main/java/com/google/cloud/trace/zipkin/StackdriverSpanConsumer.java, storage/src/main/java/com/google/cloud/trace/zipkin/StackdriverStorageComponent.java, storage/src/test/java/com/google/cloud/trace/zipkin/StackdriverStorageComponentTest.java, translation/pom.xml
Also, remove reflection workaround added as part of https://github.com/GoogleCloudPlatform/stackdriver-zipkin/pull/16
=> Update to latest cloud-trace-java version

collector/pom.xml
The collector is throwing this exception when making an outgoing gRPC call:
```
Exception in thread "grpc-default-executor-1" java.lang.IllegalArgumentException: Jetty ALPN/NPN has not been properly configured.
at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:153)
at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:130)
at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:119)
at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:90)
at io.grpc.netty.NettyChannelBuilder.createProtocolNegotiator(NettyChannelBuilder.java:265)
at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.newClientTransport(NettyChannelBuilder.java:324)
at io.grpc.internal.CallCredentialsApplyingTransportFactory.newClientTransport(CallCredentia …
```
=> Fix netty-tcnative-boringssl-static dependency

autoconfigure-storage/src/main/java/com/google/cloud/trace/zipkin/autoconfigure/ZipkinStackdriverStorageAutoConfiguration.java, collector/pom.xml, collector/src/test/java/com/google/cloud/trace/zipkin/StackdriverMockServer.java, collector/src/test/java/com/google/cloud/trace/zipkin/ZipkinCollectorIntegrationTest.java
Depending on class loading order (Mac vs. Linux,  surefire vs. executable uber jar) OpenSSL was either available, either not. As result gRPC communication was broken (see https://github.com/GoogleCloudPlatform/stackdriver-zipkin/pull/18). 
The root cause is best described in https://github.com/netty/netty-tcnative/issues/151. In short `org.apache.tomcat.jni.Library` was not loading from **netty-tcnative-boringssl-static-1.1.33.Fork23.jar**, but rather from **tomcat-embed-core-8.5.6.jar** (brought by zipkin-server -> spring-boot-starter-tomcat transitive dependency) and tcnative was failing to load proper JNI library as result. 
cc @kevinmdavis @adriancole
=> Ensure OpenSSL is available for GRPC/Netty.

autoconfigure-storage/src/main/java/com/google/cloud/trace/zipkin/autoconfigure/ZipkinStackdriverStorageProperties.java
Hopefully fixes https://github.com/spring-cloud/spring-cloud-sleuth/issues/493
Spans are getting dropped under heavy load.
I've tried to push 4500 spans over 2250 HTTP requests (2 spans per POST) with 10 threads using [default](https://github.com/GoogleCloudPlatform/stackdriver-zipkin/blob/master/autoconfigure-storage/src/main/java/com/google/cloud/trace/zipkin/autoconfigure/ZipkinStackdriverStorageProperties.java#L55) **stackdriverExecutor** params: corePoolSize = 1; maxPoolSize = 5; queueCapacity = 2000 . Unfortunately 142 spans dropped: 
```
2017-01-11 21:12:40.450  WARN 86291 --- [qtp534643569-20] zipkin.server.ZipkinHttpCollector        : Cannot store spans [7bcbf7fec05a69f0.7bcbf7fec05a69f0<:7bcbf7fec05a69f0, 438e36860fbb5d18.438e36860fbb5d18<:438e36860fbb5d18] due to …
```
=> Increase default queue capacity

autoconfigure-storage/pom.xml, autoconfigure-storage/src/main/java/com/google/cloud/trace/zipkin/autoconfigure/ZipkinStackdriverStorageAutoConfiguration.java, collector/src/test/java/com/google/cloud/trace/zipkin/ZipkinCollectorIntegrationTest.java, pom.xml, storage/pom.xml, storage/src/main/java/com/google/cloud/trace/zipkin/StackdriverStorageComponent.java
That is how metrics mightlook like on http://localhost:9411/metrics
```
"gauge.zipkin_storage.stackdriver.active_threads":5,
"gauge.zipkin_storage.stackdriver.pool_size":5,
"gauge.zipkin_storage.stackdriver.core_pool_size":1,
"gauge.zipkin_storage.stackdriver.max_pool_size":10,
"gauge.zipkin_storage.stackdriver.queue_size":20,
"counter.zipkin_storage.stackdriver.sent":99,
```
=> Added metrics for Stackdriver component

README.md
The existing doc is somewhat misleading. If you use COLLECTOR_SAMPLE_RATE=100 the collector will fail with an exception:
```
java.lang.IllegalArgumentException: rate should be between 0 and 1: was 100.0
```
=> Add docs for COLLECTOR_SAMPLE_RATE allowed values

pom.xml, translation/pom.xml, translation/src/main/java/com/google/cloud/trace/zipkin/translation/LabelExtractor.java, translation/src/main/java/com/google/cloud/trace/zipkin/translation/SpanTranslator.java, translation/src/main/java/com/google/cloud/trace/zipkin/translation/TraceTranslator.java, translation/src/test/java/com/google/cloud/trace/zipkin/translation/TraceTranslatorTest.java
This uses internal classes to perform a lot of the translation formerly
done here. By updating to latest zipkin, this also allows use of the new
POST /api/v2/spans endpoint from https://github.com/openzipkin/zipkin/issues/1499
I'm happy to support this including work to switch over to the public
zipkin2 types once they become available later this year. In the mean
time, this uses shade to ensure internal types aren't leaked.
=> Uses latest zipkin library in support of simplified json format

collector/pom.xml, collector/src/test/java/com/google/cloud/trace/zipkin/ZipkinCollectorIntegrationTest.java, pom.xml, storage/pom.xml, translation/pom.xml
Tested manually as well as unit tests. Removing the workaround allows this to work against a stock zipkin-server build.
See https://github.com/GoogleCloudPlatform/stackdriver-zipkin/pull/19#issuecomment-325263640
=> Removes boringssl workaround by updating to latest gRPC

autoconfigure-storage/src/main/java/com/google/cloud/trace/zipkin/autoconfigure/ZipkinStackdriverStorageProperties.java, pom.xml
* Update the zipkin version to 2.5.0
Fixes https://github.com/GoogleCloudPlatform/stackdriver-zipkin/issues/57
=> Fix bug related to api host not having the port.

autoconfigure/storage-stackdriver/pom.xml
avoids this crash
```
Caused by: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;CLjava/lang/Object;)V
at io.grpc.Metadata$Key.validateName(Metadata.java:628) ~[grpc-core-1.11.0.jar!/:1.11.0]
at io.grpc.Metadata$Key.<init>(Metadata.java:636) ~[grpc-core-1.11.0.jar!/:1.11.0]
at io.grpc.Metadata$Key.<init>(Metadata.java:566) ~[grpc-core-1.11.0.jar!/:1.11.0]
at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:740) ~[grpc-core-1.11.0.jar!/:1.11.0]
at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:735) ~[grpc-core-1.11.0.jar!/:1.11.0]
at io.grpc.Metadata$Key.of(Metadata.java:592) ~[grpc-core-1.11.0.jar!/:1.11.0]
```
=> Packages new guava in the module as it is later than spring boot

README.md, translation-stackdriver/src/main/java/zipkin2/translation/stackdriver/SpanTranslator.java
We've had a number of support issues around translation. This adds debug
logging which can help determine the cause of failures.
```
2018-04-09 13:51:19.279 DEBUG [/] 7295 --- [   XNIO-2 I/O-2] z.t.stackdriver.SpanTranslator           : >> translating zipkin span: {"traceId":"e7d33ab8fe95b3cb","id":"e7d33ab8fe95b3cb","kind":"SERVER","name":"get /","timestamp":1523253078006004,"duration":158196,"localEndpoint":{"serviceName":"frontend","ipv4":"192.168.1.113"},"remoteEndpoint":{"ipv6":"::1","port":60162},"tags":{"http.method":"GET","http.path":"/","mvc.controller.class":"Frontend","mvc.controller.method":"callBackend"}}
2018-04-09 13:51:19.281 DEBUG [/] 7295 --- [   XNIO-2 I/O-2] z.t.stackdriver.SpanTranslator           : << translated to stackdriver span: span_id: 16704760009066918859 …
```
=> Logs translation when SpanTranslator is at FINE/DEBUG level

translation-stackdriver/src/main/java/zipkin2/translation/stackdriver/SpanTranslator.java, translation-stackdriver/src/test/java/zipkin2/translation/stackdriver/SpanTranslatorTest.java
Associates them with SPAN_KIND_UNSPECIFIED on the Stackdriver side,
since, according to CONSUMER and PRODUCER's Javadoc, they don't have
trace IDs, therefore shouldn't be either SpanKind.RPC_CLIENT or
SpanKind.RPC_SERVER.
=> Adds span kinds CONSUMER and PRODUCER

sender-stackdriver/README.md, translation-stackdriver/src/main/java/zipkin2/translation/stackdriver/SpanTranslator.java, translation-stackdriver/src/main/java/zipkin2/translation/stackdriver/TraceTranslator.java, translation-stackdriver/src/test/java/zipkin2/translation/stackdriver/SpanTranslatorTest.java, translation-stackdriver/src/test/java/zipkin2/translation/stackdriver/TraceTranslatorTest.java
Applications can be configured to not share IDs across client and
server. This is more reliable than rewriting IDs and also doesn't
conflict with log statements which have the correct IDs in them.
Fixes #67
=> Removes the ID rewriting code in favor of application configuration

pom.xml, propagation-stackdriver/pom.xml, propagation-stackdriver/src/main/java/zipkin2/propagation/stackdriver/CompositeExtractor.java, propagation-stackdriver/src/main/java/zipkin2/propagation/stackdriver/StackdriverTracePropagation.java, propagation-stackdriver/src/main/java/zipkin2/propagation/stackdriver/XCloudTraceContextExtractor.java, propagation-stackdriver/src/test/java/zipkin2/propagation/stackdriver/XCloudTraceContextExtractorTest.java
This propagation re-uses B3Propagation's injector, while adding a new
CompositeExtractor concept that aims at extracting multiple trace IDs,
in order.
In this case, we're interested in extracting the trace ID from the
'x-cloud-trace-context' header, followed by 'X-B3-TraceId'.
Fixes https://github.com/spring-cloud/spring-cloud-gcp/issues/703
=> Implements GCP propagation

pom.xml, propagation-stackdriver/src/main/java/zipkin2/propagation/stackdriver/StackdriverTracePropagation.java, propagation-stackdriver/src/main/java/zipkin2/propagation/stackdriver/XCloudTraceContextExtractor.java, propagation-stackdriver/src/test/java/zipkin2/propagation/stackdriver/XCloudTraceContextExtractorTest.java
App Engine generates span IDs that are longer than a long.
Given that Stackdriver Trace doesn't support trace joins, the incoming
span ID is useless anyway.
So, to save the time of parsing and creating a new long object, we don't
do that and, instead, set 1L as the span ID value, which Brave will
always regenerate anyways.
=> Fixes issue where span ID is bigger than long in GAE

autoconfigure/storage-stackdriver/src/main/java/zipkin/autoconfigure/storage/stackdriver/ZipkinStackdriverStorageAutoConfiguration.java
This allows OpenJDK 1.8 images to live longer (without needing to install OpenSSL). Same approach as Netty uses
See https://github.com/openzipkin/docker-jre-full/issues/9
=> Allows ALPN extension when OpenSSL is not available

translation-stackdriver/src/main/java/zipkin2/translation/stackdriver/LabelExtractor.java, translation-stackdriver/src/test/java/zipkin2/translation/stackdriver/LabelExtractorTest.java
We had an issue where stackdriver-zipkin (now zipkin-gcp) got stuck in an infinite loop, trying to resend a trace that had a very large SQL statement as a value for one of the tags/labels.
Shorten long tag values to keep within the limits allowed by Stackdriver Trace when extracting labels.
=> Shorten tag/label values that are too large for Stackdriver

propagation-stackdriver/README.md, propagation-stackdriver/src/main/java/zipkin2/propagation/stackdriver/StackdriverTracePropagation.java, propagation-stackdriver/src/test/java/zipkin2/propagation/stackdriver/StackdriverTracePropagationTest.java
Addresses mismatch between extractor (which used to prefer X-cloud headers) and injector (which propagates b3 headers) by preferring b3 headers, when available.
Fixes #96 .
=> Prefer b3 to x-cloud-trace in extractor

propagation-stackdriver/src/main/java/zipkin2/propagation/stackdriver/XCloudTraceContextExtractor.java, propagation-stackdriver/src/test/java/zipkin2/propagation/stackdriver/XCloudTraceContextExtractorTest.java
This adds support to process the TRACE_TRUE option to behave like x-b3-sampled header.
Given a trace of form: `x-cloud-trace-context: TRACE_ID/SPAN_ID;o=TRACE_TRUE`
If TRACE_TRUE
- is `true`: Force the request to be traced
- is `false`: Force the request not to be traced
- is not present: Defer the trace/no-trace decision to the sampler
Fixes https://github.com/spring-cloud/spring-cloud-gcp/issues/749
@meltsufin @elefeint PTAL
=> Handle the TRACE_TRUE option in GCP trace header

propagation-stackdriver/README.md, propagation-stackdriver/src/main/java/zipkin2/propagation/stackdriver/XCloudTraceContextExtractor.java, propagation-stackdriver/src/test/java/zipkin2/propagation/stackdriver/StackdriverTracePropagationTest.java, propagation-stackdriver/src/test/java/zipkin2/propagation/stackdriver/XCloudTraceContextExtractorTest.java
This cleans up the XCloudTraceContextExtractor following up from #103.
I made a few changes here:
- Instead of setting a default span ID of 1, I set it to 0.
- You can now pass in x-cloud-trace-context in the form of `TRACE_ID/0;o=1`. If 0 is passed in, we wil interpret this as omitting a span ID by returning a `TraceIdContext` object, which reflects the intention described in [Stackdriver docs](https://cloud.google.com/trace/docs/troubleshooting) see section "How do I force a request to be traced?" 
> SPAN_ID is the decimal representation of the (unsigned) span ID. It should be 0 for the first span in your trace. 
- cleans up the 'o=' options parsing as mentioned in #103.
PTAL @meltsufin
=> Cleanup Cloud Trace Context Extractor

autoconfigure/pom.xml, autoconfigure/storage-stackdriver/pom.xml, autoconfigure/storage-stackdriver/src/main/java/zipkin/autoconfigure/storage/stackdriver/CredentialsDecoratingClient.java, autoconfigure/storage-stackdriver/src/main/java/zipkin/autoconfigure/storage/stackdriver/ZipkinStackdriverStorageAutoConfiguration.java, autoconfigure/storage-stackdriver/src/test/java/zipkin2/storage/stackdriver/StackdriverMockServer.java, autoconfigure/storage-stackdriver/src/test/java/zipkin2/storage/stackdriver/ZipkinStackdriverStorageAutoConfigurationTest.java, autoconfigure/storage-stackdriver/src/test/java/zipkin2/storage/stackdriver/ZipkinStackdriverStorageIntegrationTest.java, pom.xml, sender-stackdriver/pom.xml, storage-stackdriver/pom.xml, storage-stackdriver/src/main/java/zipkin2/storage/stackdriver/StackdriverSpanConsumer.java, storage-stackdriver/src/main/java/zipkin2/storage/stackdriver/StackdriverStorage.java, storage-stackdriver/src/test/java/zipkin2/storage/stackdriver/ITStackdriverSpanConsumer.java, translation-stackdriver/pom.xml
One concern is the API change in storage-stackdriver's `Builder` not sure what the API guarantee on that is.
Only ran integration tests.
Fixes #119
=> Use armeria-grpc client in storage-stackdriver.

.mvn/wrapper/MavenWrapperDownloader.java, .mvn/wrapper/maven-wrapper.properties, CONTRIBUTING.md, README.md, autoconfigure/pom.xml, autoconfigure/storage-stackdriver/README.md, autoconfigure/storage-stackdriver/pom.xml, benchmarks/pom.xml, mvnw, mvnw.cmd, pom.xml, sender-stackdriver/pom.xml, storage-stackdriver/pom.xml, translation-stackdriver/pom.xml
There is a problem at runtime eventhough grpc-core.jar is inside stackdriver.jar
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.grpc.Status
at com.linecorp.armeria.internal.grpc.HttpStreamReader.onNext(HttpStreamReader.java:137) ~[armeria-grpc-0.84.0.jar!/:?]
at com.linecorp.armeria.internal.grpc.HttpStreamReader.onNext(HttpStreamReader.java:52) ~[armeria-grpc-0.84.0.jar!/:?]
at com.linecorp.armeria.common.stream.DeferredStreamMessage$ForwardingSubscriber.onNext(DeferredStreamMessage.java:305) ~[armeria-0.84.0.jar!/:?]
at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberWithElements(DefaultStreamMessage.java:342) ~[armeria-0.84.0.jar!/:?]
at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.ja …
```
=> Updates versions notably to ASF Zipkin

autoconfigure/storage-stackdriver/src/main/java/zipkin/autoconfigure/storage/stackdriver/ZipkinStackdriverStorageAutoConfiguration.java
Happened to notice this when wanting to copy this code into armeria
=> Allow running zipkin-gcp on Java 9+ without ALPN

autoconfigure/storage-stackdriver/pom.xml, autoconfigure/storage-stackdriver/src/main/java/zipkin/autoconfigure/storage/stackdriver/ZipkinStackdriverStorageAutoConfiguration.java, pom.xml, storage-stackdriver/pom.xml, storage-stackdriver/src/main/java/zipkin2/storage/stackdriver/StackdriverSpanConsumer.java, storage-stackdriver/src/main/java/zipkin2/storage/stackdriver/StackdriverStorage.java, translation-stackdriver/pom.xml
Now `storage-stackdriver` doesn't depend on gRPC or guava.
I was a bit unsure what to do with it's protobuf dependency as armeria-grpc-protocol doesn't depend on it so it wouldn't control the version. I've never seen an incompatible API in protobuf before though and recommend just pinning to latest version like here.
=> Use UnaryGrpcClient in storage-stackdriver instead of gRPC stubs.

autoconfigure/storage-stackdriver/README.md, autoconfigure/storage-stackdriver/src/main/java/zipkin/autoconfigure/storage/stackdriver/ZipkinStackdriverStorageAutoConfiguration.java, autoconfigure/storage-stackdriver/src/main/java/zipkin/autoconfigure/storage/stackdriver/ZipkinStackdriverStorageProperties.java, autoconfigure/storage-stackdriver/src/main/resources/zipkin-server-stackdriver.yml
This makes it easier to see grpc errors as they are in the trailers sometimes.
Use `STACKDRIVER_HTTP_LOGGING=headers` to see grpc status. Note this doesn't include body as it is complicated and also it is binary. You can still see grpc errors looking only at the headers.
Ex. `Requested entity was not found.` when you misconfigure the application name
```
2019-08-16 10:45:29.036  INFO 47885 --- [-worker-nio-2-4] c.l.a.c.l.LoggingClient                  : Request: {startTime=2019-08-16T02:45:29.023Z(1565923529023099), length=399B, duration=10424µs(10424447ns), scheme=none+h2, headers=[:method=POST, :path=/google.devtools.cloudtrace.v2.TraceService/BatchWriteSpans, :authority=cloudtrace.googleapis.com, :scheme=https, te=trailers, content-length=399, authorization=Bearer REDACTED, …
```
=> Adds STACKDRIVER_HTTP_LOGGING=headers to see grpc status

pom.xml, storage-stackdriver/src/main/java/com/linecorp/armeria/common/grpc/protocol/UnaryGrpcClient.java, storage-stackdriver/src/main/java/zipkin2/storage/stackdriver/StackdriverSpanConsumer.java, storage-stackdriver/src/main/java/zipkin2/storage/stackdriver/StackdriverStorage.java, storage-stackdriver/src/main/java/zipkin2/storage/stackdriver/UnaryGrpcClient.java
temporary until https://github.com/line/armeria/pull/1998 We need to get things layered on this to work, most notably health checks #131, and it isn't a huge deal to C&P one ASL file I think.
@trustin @anuraaga I changed our license config to ensure vendoring doesn't impact the file pasted temporarily. When ready, we simply revert this commit.
=> Adds patch until Armeria 0.91

.travis.yml, autoconfigure/storage-stackdriver/pom.xml, autoconfigure/storage-stackdriver/src/test/java/zipkin2/storage/stackdriver/ITZipkinStackdriverStorage.java, pom.xml, sender-stackdriver/pom.xml, sender-stackdriver/src/test/java/zipkin2/reporter/stackdriver/ITStackdriverSender.java
For #130 
Added integration test for Zipkin Stackdriver Reporter, which is a different path than the Stackdriver Sender.
=> Added integration test for Stackdriver Storage with autoconfiguration

translation-stackdriver/src/main/java/zipkin2/translation/stackdriver/AttributesExtractor.java, translation-stackdriver/src/test/java/zipkin2/translation/stackdriver/AttributesExtractorTest.java
Span object stores `localEndpoint.serviceName` empty string as null so `.isEmpty()` throws NullPointerException.
=> Make serviceName check null-safe

README.md
We had a troubleshooting session on https://gitter.im/openzipkin/zipkin with @z-oo
basically unless you put the log level wider, you can't see any errors caused by translation bugs. Ex.
this:
```bash
curl -X POST -s localhost:9411/api/v2/spans -H'Content-Type: application/json' -d '[{"traceId":"fe1583ed5be1b96cf40538f958ca97a6","id":"96169d26c53f25ab","name":"loader::unload","timestamp":1568360755828060,"duration":124,"localEndpoint":{"ipv6":"::1"}}]'
```
causes an exception, but you'd not see the exception if you only looked at the translation logger.
```
2019-09-13 08:05:45.086 DEBUG 1 --- [cking-tasks-1-1] z.t.s.SpanTranslator                     : >> translating zipkin span: {"traceId":"fe1583ed5be1b96cf40538f958ca97a6","id":"96169d26c53f25ab","name":"loader::unload","timestamp":156836 …
```
=> widen logging scope to zipkin2

propagation-stackdriver/src/main/java/zipkin2/propagation/stackdriver/CompositeExtractor.java, propagation-stackdriver/src/main/java/zipkin2/propagation/stackdriver/StackdriverTracePropagation.java, propagation-stackdriver/src/main/java/zipkin2/propagation/stackdriver/XCloudTraceContextExtractor.java, propagation-stackdriver/src/test/java/zipkin2/propagation/stackdriver/StackdriverTracePropagationTest.java, propagation-stackdriver/src/test/java/zipkin2/propagation/stackdriver/XCloudTraceContextExtractorTest.java
In a strange state that local build doesn't catch these for some reason but should be fine finally.
=> Add last license updates

pom.xml, propagation-stackdriver/src/main/java/zipkin2/propagation/stackdriver/XCloudTraceContextExtractor.java
`spring-cloud-sleuth` is already using the latest version of Brave, but `zipkin-gcp` lagged. 
In between, `HexCodec` helper class got moved into a subpackage in openzipkin/brave#1193.
This PR will allow `spring-cloud-gcp` to upgrade to the latest `spring-cloud-sleuth` without triggering runtime class incompatibility (`Caused by: java.lang.NoClassDefFoundError: brave/internal/HexCodec`).
=> Upgrades brave and updates HexCodec import to correct package

.github/workflows/docker-tests.yml, .github/workflows/docker/docker-compose.test.yml, .travis.yml, RELEASE.md, docker/build_image, travis/publish.sh
We've long since gotten to the bottom of this. Rather than always skipping the
license plugin in CI, causing a poor experience for people who have local builds
fail over it, this re-enables after underscoring the CI config needed to make it
work.
After this change, pull requests won't be green unless the headers are correct.
=> Re-enables license plugin

RELEASE.md
Follow up on https://github.com/openzipkin/zipkin-gcp/issues/182#issuecomment-724445747
The verbiage is only limited to GCP Service Account configuration. There are additional Travis-mentions for releasing etc - those verbiages are not updated in this PR.
=> Updated credentials verbiage for GitHub Actions

.dockerignore, build-bin/docker/docker_test_image, build-bin/maven/maven_build, build-bin/maven/maven_build_or_unjar, build-bin/maven/maven_release, build-bin/maven/maven_unjar, pom.xml
When there was no prior build, this would have not worked
```bash
build-bin/docker/docker_build openzipkin/zipkin-gcp:test
```
=> Fixes on-demand build in docker

docker/Dockerfile, pom.xml
Updated the Zipkin version to address [#Issue-194](https://github.com/openzipkin/zipkin-gcp/issues/194)
=> Update Zipkin to address CVE-2021-44228

benchmarks/pom.xml, module/pom.xml, pom.xml, propagation-stackdriver/pom.xml, sender-stackdriver/pom.xml, storage-stackdriver/pom.xml, translation-stackdriver/pom.xml
I ran `./mvnw com.mycila:license-maven-plugin:format` to make the license plugin happy. The license check has been causing failures on some pull requests. See https://github.com/openzipkin/zipkin-gcp/pull/202#issuecomment-1693883846 and https://github.com/openzipkin/zipkin-gcp/pull/197#issuecomment-1007077302
=> Update license plugin and headers

build-bin/README.md, build-bin/docker-compose-zipkin-gcp.yml, module/pom.xml, module/src/main/java/zipkin/module/storage/stackdriver/CredentialsDecoratingClient.java, pom.xml
armeria was this https://github.com/line/armeria/commit/ce03ff4333de56c3facf515bf0587245ca36aa4d
also updates to final zipkin lib versions.
=> fixes issues around missing gson and armeria decoration

benchmarks/pom.xml, collector-pubsub/pom.xml, docker/Dockerfile, module/pom.xml, pom.xml, propagation-stackdriver/pom.xml, propagation-stackdriver/src/main/java/brave/propagation/stackdriver/StackdriverTracePropagation.java, sender-pubsub/pom.xml, sender-stackdriver/pom.xml, storage-stackdriver/pom.xml, translation-stackdriver/pom.xml
See https://github.com/openzipkin/brave/pull/1396 about Propagation and Brave 6.0
=> deps: updates to latest zipkin versions

pom.xml, propagation-stackdriver/src/main/java/brave/propagation/stackdriver/StackdriverTracePropagation.java, propagation-stackdriver/src/main/java/zipkin2/propagation/stackdriver/StackdriverTracePropagation.java
Note after we release, we should bump major when updating to zipkin-reporter 3.0.1
=> Prepares for release by updating to Brave 5.18

.github/workflows/create_release.yml, .github/workflows/deploy.yml, .github/workflows/test.yml, README.md, benchmarks/pom.xml, collector-pubsub/pom.xml, docker/Dockerfile, module/README.md, module/pom.xml, module/src/test/java/zipkin2/storage/stackdriver/ITZipkinStackdriverStorage.java, module/src/test/java/zipkin2/storage/stackdriver/StackdriverMockServer.java, pom.xml, sender-stackdriver/src/test/java/zipkin2/reporter/stackdriver/ITStackdriverSender.java, storage-stackdriver/pom.xml
This updates server modules to Zipkin 3, Spring Boot 3 and JRE 17. It leaves the client side modules at Java 8.
In order to compile the server module, we can no longer compile with JDK 11.
See https://github.com/openzipkin/zipkin/pull/3684
=> Updates to Zipkin 3, Spring Boot 3 and JRE 17

.github/workflows/create_release.yml, .github/workflows/deploy.yml, .github/workflows/docker_push.yml, .github/workflows/lint.yml, .github/workflows/test.yml, build-bin/README.md, build-bin/configure_lint, build-bin/lint
This also fixes lint on the test workflow
=> ci: ensures markdown config doesn't trigger java tests

build-bin/docker-compose-zipkin-gcp.yml, docker/Dockerfile, encoder-stackdriver-brave/src/main/java/zipkin2/reporter/stackdriver/brave/AttributesExtractor.java, encoder-stackdriver-brave/src/test/java/zipkin2/reporter/stackdriver/brave/SpanTranslatorTest.java, module/src/main/java/zipkin/module/storage/stackdriver/ZipkinStackdriverStorageModule.java, module/src/test/java/zipkin2/storage/stackdriver/ZipkinStackdriverStorageIntegrationTest.java, pom.xml, propagation-stackdriver/src/test/java/brave/propagation/stackdriver/XCloudTraceContextExtractorTest.java, sender-pubsub/src/test/java/zipkin2/reporter/pubsub/PubSubSenderTest.java, sender-stackdriver/src/test/java/zipkin2/reporter/stackdriver/AsyncReporterStackdriverSenderTest.java, translation-stackdriver/src/test/java/zipkin2/translation/stackdriver/SpanTranslatorTest.java
@provegard mentioned on gitter that we are getting an openssl error. I think the check is no longer valid after we switched to latest JRE + spring boot 3, as when I remove the check, the docker image (alpine JRE 21) works fine. So, I'm removing the check and in worst case, if someone has a misconfiguration, they get a late error in /health, but we don't get a false report for everybody else.
Traces created with https://github.com/openzipkin/brave-example/tree/master/armeria and self-tracing too.
I ran the locally build docker image like so, configured with `Trace Agent` role
```bash
$ docker run --rm -p 9411:9411 --name zipkin-gcp -e SELF_TRACING_ENABLED=true  -e STORAGE_TYPE=stackdriver   -e GOOGLE_APPLICATION_CREDENTIALS=/zipkin/.gcp/credentials.json   -e …
```
=> removes invalid openssl check and bumps deps

.github/workflows/lint.yml, .github/workflows/security.yml, RELEASE.md, SECURITY.md
This adds SECURITY.md and a scanning workflow, using Trivy. In particular, this clarifies what we use to scan for vulnerabilities (Trivy, not anything else), and the only channel likely to be responded to on a significant issue (zipkin-admin email, not advisories as people ignored them).
This is the same approach as approved and merged in https://github.com/openzipkin/zipkin-reporter-java/pull/267
=> Adds SECURITY.md and scanning workflow

encoder-stackdriver-brave/src/main/java/zipkin2/reporter/stackdriver/brave/AttributesExtractor.java, encoder-stackdriver-brave/src/test/java/zipkin2/reporter/stackdriver/brave/AttributesExtractorTest.java
=> Fix NPE in brave-encoder-stackdriver when local ip is not set

.github/workflows/create_release.yml, .github/workflows/deploy.yml, .github/workflows/docker_push.yml, .github/workflows/lint.yml, .github/workflows/security.yml, .github/workflows/test.yml, collector-pubsub/src/test/java/zipkin2/collector/pubsub/PubSubCollectorTest.java, docker/Dockerfile, pom.xml
=> Update infra and dependencies

encoder-stackdriver-brave/src/main/java/zipkin2/reporter/stackdriver/brave/SpanTranslator.java, encoder-stackdriver-brave/src/test/java/zipkin2/reporter/stackdriver/brave/SpanTranslatorTest.java, encoder-stackdriver-brave/src/test/java/zipkin2/reporter/stackdriver/brave/TestObjects.java, translation-stackdriver/src/main/java/zipkin2/translation/stackdriver/SpanTranslator.java, translation-stackdriver/src/test/java/zipkin2/translation/stackdriver/SpanTranslatorTest.java
From Spring Cloud Sleuth to Spring Framework 6, the tags on HTTP spans produced changed. This updates the SpanTranslator to handle the Spring 6 tags.
Resolves #228
=> Translate Spring 6 HTTP spans to Stackdriver convention

.github/workflows/security.yml, RELEASE.md, build-bin/configure_lint
So we can check before releasing that the release branch is up-to-date.
=> Allow manual runs of the security check
